services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - nginx_data:/data
    ports:
      - 80:80
    depends_on:
      - web1
      - web2
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  web1:
    build: ./web01/usr/src/app
    restart: always
    volumes:
      - web01_data:/data
    ports:
      - 81:5000

  web2:
    build: ./web02/usr/src/app
    restart: always
    volumes:
      - web02_data:/data
    ports:
      - 82:5000

volumes:
  nginx_data:
  redis_data:
  web01_data:
  web02_data:
